### PR TITLE
build instructions for ulimit increase on OS X

### PR DESCRIPTION
**Pull request by vielmetti**
reference #891

### CODE REVIEW

**Comment by adityab** [comment]
ok to test

**Comment by kossebau** [comment]
@vielmetti Make sense to me, thanks for the patch.
Could you do us a favour and rebase your patch to the latest master of WebODF? That way we can keep our nice slim history graph when we merge your patch :)

**Comment by kossebau** [comment]
@vielmetti So some tweet web service brings me news about your efforts to learn how to rebase :)

Please try this, and if there is an error, stop and ask, best by talking to us on irc channel #webodf to help you (see http://webodf.org/community/index.html#irc )
```
git checkout master
git fetch https://github.com/kogmbh/WebODF.git master
git merge --ff-only FETCH_HEAD
git rebase master patch-1
git push github patch-1 -f 
```
In the last line `github` needs to be replaced with the repo name that you are using for your github repo of webodf, perhaps it is `origin`.

What those lines do: first 3 are getting the latest commits from the real WebODF repo and adding them to your local master branch (--ff-only ensures they are only added if there are no conflicting commits which need merging, to ensure the result is identical to the original branch).
4th is then doing the actual rebase, changing your branch patch-1 to be based on the latest state of the master branch (which is now reflecting the master branch of the original repo).
And the last line pushes your updated patch-1 branch to your github repo, overwriting the old branch due to -f (as in: force).

**Comment by kossebau** [comment]
@vielmetti Seems you are busy with other stuff, no problem. Will apply your commit myself now :)

**Comment by kossebau** [comment]
Thanks again, rebased commit merged now manually.

**Comment by vielmetti** [comment]
thanks!

**Pull request closed without merging**
