### PR TITLE
Remove HTML rendering of logging out of normal BrowserRuntime

### LINKED ISSUE #587: remove use of innerHTML
Using innerHTML is a security problem. Javascript snippets from a document might be interpreted as code and run by passing them to innerHTML. All uses of innerHTML should be removed.

### PR DESCRIPTION
**Pull request by kossebau**
Fixes #587, by moving the last innerHTML out of production code. Also will no more 

#869 will not yet be solved by this, as I had no clear idea yet if semantic markup of the data passed to the logger is something needed outside tests and worth any bigger effort. 
At least I see the value in having the log output being rendered additionally into the test result presentation. Possibly the marked-up HTML should simply not be done via `runtime.log` but explicitely.
Left for another free time slot with more ideas or for somebody else :)

Additionally moves UnitTester code into test dirs & no longer compile into webodf.js (356935 -> 349611). Still covered by jslint &closure strict compiling, so should be no problem.

### CODE REVIEW

**Comment by kossebau** [comment]
@vandenoever Was there any other reason to have `UnitTester.js` in `libs/core` I might not be aware of?

**Comment by kossebau** [comment]
Noone around to review, so let's get it in.

**Comment by peitschie** [comment]
I was overseas on a beach for a while :sunglasses:

I'm not even sorry I missed reviewing this :stuck_out_tongue:

**Comment by kossebau** [comment]
That's why I made sure there should be left a follow-up PR on this topic, so you will not miss out completely ;)

**Pull request merged**
