### PR TITLE
Make OdtDocument.getMemberIds return ALL memberIds

### PR DESCRIPTION
**Pull request by adityab**
... and not just those of cursors. Surprised I never noticed this before.

### CODE REVIEW

**Comment by peitschie** [comment]
Indeed, a rather interesting block of code. Is it possible to add a test for this to the existing ``OdtDocumentTests`` suite?

**Comment by adityab** [comment]
Done.

**Comment by peitschie** [comment]
I've just had a poke through source, and there's a bunch of places using ``getMemberIds`` that seem to assume that member = cursor. Are you able to have a look at these as part of this patch as well?

The primary ones that will cause issues are in ``DocumentValidator.js``, ``Bella.js``, ``splitscreeneditor.js`` has some confusing terminology (advertising these under the property ``cursors``)

**Comment by adityab** [comment]
Good catch. I updated those parts, and also `TrivialUndoManager.js`. Unfortunately with the added type annotations I'm hitting a `RangeError` when running `cmake`, which is basically really confusing. It appears that the dependency graph gets too huge and the `eval` here blows up https://github.com/kogmbh/WebODF/blob/master/webodf/lib/runtime.js#L1840.

The extra commit which triggers the issue is in this branch https://github.com/adityab/WebODF/tree/fix-memberids-getter-RangeError.

That said, those other references to `getMemberIds` will never break at this stage because Bella/splitscreeneditor don't have cases where members and cursors are unbalanced. So I'd say we ought to just merge this before trying to fix the `RangeError`.

**Comment by peitschie** [comment]
> So I'd say we ought to just merge this before trying to fix the RangeError.

That doesn't really buy much advantage, unless you need this in master for some specific reason? :smile_cat:  

If you do land this one, you'll need to raise an issue or something to track the fix-ups anyways, so it's probably more work to land this patch and then fix master. I'd prefer the fix for the range error is figured out now, and either combed into this PR, or raised another PR this one can be rebased on to. After all, you're going to hit the range error again within the next few patches most likely..

**Comment by adityab** [comment]
> That doesn't really buy much advantage, unless you need this in master for some specific reason?

Yep, which is that I need this particular fix landed in time for the next release (which I guess @kossebau would tag tomorrow) - for the reason that Manticore's phantomjs snapshotting module needs this method to work correctly (when requested, it generates a snapshot of the document, added members, and cursor positions).

**Comment by peitschie** [comment]
> Yep, which is that I need this particular fix landed in time for the next release (which I guess @kossebau would tag tomorrow) - for the reason that Manticore's phantomjs snapshotting module needs this method to work correctly (when requested, it generates a snapshot of the document, added members, and cursor positions).

So your product is tied to WebODF master releases? I can speak from experience that being connected in that fashion will give you more stress than you probably want. Any reason you can't cut these releases from your own branch instead, whilst the PR makes it's way through review at a reasonable (and unstressed) pace?

**Comment by adityab** [comment]
Ok, will try that then. I'll see if I can do something about the RangeError over the weekend...

**Comment by adityab** [comment]
As you pointed out on IRC, this error actually shows up when there's a cyclic dependency. Fixed. :)

**Comment by peitschie** [comment]
Looks good to me! Thanks for fixing up those additional references.

Please :shipit:  (I still wish I understood why shipping requires a mouse in a cute hat... but oh well)

**Comment by adityab** [comment]
Hehe, thanks for the review.

**Pull request merged**
